### ISSUE TITLE
Using Packages on Azure App Services

### ISSUE THREAD

**Issue by DamolAAkinleye** [frinyvonnick/node-html-to-image#181]
We are trying to use the package on the Azure App services. 

However, we are getting the unable to load browser error when using it via the PAAS Services on azure. 

I have seen documentation for Heroku, however, this approach of installing buildpack does not work for Azure. Is there any sample we can use that has worked around this problem?

**Comment by frinyvonnick** [comment]
Hello @DamolAAkinleye 👋 

Thank you for opening this issue 🙏 I just released a version that lets you customize which puppeteer library node-html-to-image will use. This feature was asked for cloud usages. It might help you making it work.

Here is the documentation : https://github.com/frinyvonnick/node-html-to-image#using-different-puppeteer-libraries

Otherwise you might find some help in the troubleshooting section of puppeteer documentation : https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

If it fixes your issue please, close it 😄

**Comment by frinyvonnick** [comment]
Without any new answer I close this issue. Feels free to reopen it 👍
