### ISSUE TITLE
Issue in using a custom ttf font within an express app 

### ISSUE THREAD

**Issue by shameersalim** [frinyvonnick/node-html-to-image#55]
Hi
The library is wonderful and works perfectly. I want to know if I can use a custom ttf font deployed as part of my express app. 
Sample code that doesnt work. 

app.get(`/api/tweet/render`, async function(req, res) {
    const htmlString = `
    <html>
    <head>
    <style>
      body {
        width: 1600px;
        height: 2000px;
      }

      @font-face {
        font-family: "LCSmith_TypeWriter";
        src: url("./static/fonts/LCSmith_TypeWriter.ttf");
      }
    </style>
  </head>
    <body> Some text goes here
    </body></html>
    `;
    const image = await nodeHtmlToImage({
      html: htmlString,
    });
    res.writeHead(200, { 'Content-Type': 'image/png' });
    res.end(image, 'binary');
  });

Please let me know if I am doing something wrong.

**Comment by frinyvonnick** [comment]
Hi @shameersalim 👋 

Thank you for posting this issue. I recommend you to use webfonts like in the snippet of this [message](https://github.com/frinyvonnick/node-html-to-image/issues/33#issuecomment-635151349). Otherwise here is an [alternative](https://github.com/puppeteer/puppeteer/issues/3183#issuecomment-635844987) to load custom font you have locally.

**Comment by frinyvonnick** [comment]
I close this issue since there is no answer for a long time. Feel free to reopen it.
